import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AirBnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <h1 className='mt-10 text-4xl text-center font-bold'>AirBnb Clone</h1>
      </main>

      <footer>
    
      </footer>
    </div>
  )
}
